Cypress.Commands.add('completeRegistration', () => {
  cy.visit('/2')
  cy.get('[qa-ref="form-one-first-name"]').type('Kevin')
  cy.get('[qa-ref="form-one-last-name"]').type('Martinez')
  cy.get('[qa-ref="form-one-username"]').type('test')
  cy.get('[qa-ref="next-button"]').click()
  cy.get('[qa-ref="form-two-email"]').type('email@test.com')
  cy.get('[qa-ref="form-two-agree-to-terms"]').click()
  cy.get('[qa-ref="next-button"]').click()
})
